### ISSUE TITLE
Type here your code refactor ideas

### ISSUE THREAD

**Issue by szymon-owczarzak** [wttech/cogboard#237]
### Short Description
In this task we gather ideas for code refactor. Add them as comments.

**Comment by szymon-owczarzak** [comment]
Please check if the logic within Board.kt and Widget.kt could be simplified/refactored 
(@JsonIgnore, @JsonAnySetter, @JsonAnyGetter)

**Comment by YellowFlash525** [comment]
I think that it will be good idea to create custom component for IconBlock with Tooltip

**Comment by YellowFlash525** [comment]
Also I think about creating something like template for JiraBucketInput, ToDoListInput and LinkListInput

**Comment by YellowFlash525** [comment]
Maybe some unit tests for react?

**Comment by YellowFlash525** [comment]
We need to check the components, whether it is possible to simplify / standardize something in terms of styles
