### ISSUE TITLE
Widget | Add thresholds for Jira query

### ISSUE THREAD

**Issue by arkadiusz-wojda-wttech** [wttech/cogboard#262]
### Short Description
Add possibility to enable/disable warnings/alerts for each JIRA status in the widget if it reaches certain number

#### Solution
Add a checkbox (true/false) for each JIRA status that will allow to enable/disable the threshold so when i.e.: tickets in status CODE REVIEW reaches number of 3 then **the widget line** with tickets in Code Review will change color to yellow, and when it is 5 or more then the color will turn red

### Acceptance Criteria
 - [ ] Admin can enable the feature for each configured JIRA status
-  [ ] Admin can use some sort of slider to easily change the threshold number both for warnings and alerts
 - [ ] Widget line with JIRA status will change color to yellow or red if the threshold is enabled and certain number has been reached

**Comment by GrzegorzBednarski** [comment]
Duplicated https://github.com/Cognifide/cogboard/issues/288

**Comment by GrzegorzBednarski** [comment]
Tested & accepted
