### ISSUE TITLE
Widget | Possibility to reorder Lists

### ISSUE THREAD

**Issue by basia-wulnikowska** [wttech/cogboard#288]
### Short Description
There are 4 types of lists: To Do list, Link list & Random picker (old person draw), jira buckets. Those lists are sorted with order of being added and user can't change their order. We want to change it.

### Solution 
Implement drag&drop to all types of lists so user can move list item to other position.

##### Additional notes
Drag & drop is already impemented in boards list - maybe we can reuse this solution?)

**Comment by GrzegorzBednarski** [comment]
Tested & accepted
