### ISSUE TITLE
Widget | Title lost when expandable content set

### ISSUE THREAD

**Issue by basia-wulnikowska** [wttech/cogboard#301]
### Description
When widget without icon (like text) has no title, and has expandable text, then menu and roll up icons are to close to each other

 ### Example widget:
On Testboard 1, remove Title from Wrapped Text Widget, save and expand content.
<img width="223" alt="2020-10-23_13h24_21" src="https://user-images.githubusercontent.com/40600031/96998049-24cf1a80-1533-11eb-9bc5-67d2d924eccc.png">

**Comment by GrzegorzBednarski** [comment]
Invalid
