### ISSUE TITLE
Scroll on non-expandable text widget with no title not working

### ISSUE THREAD

**Issue by basia-wulnikowska** [wttech/cogboard#302]
### Description
When text widget has non-expandable content, and no Title, then scrolling is impossible. Text is being cut. Fix should be implemented to add scroll in this case.

<img width="231" alt="2020-10-23_13h31_58" src="https://user-images.githubusercontent.com/40600031/96998665-251be580-1534-11eb-88af-4396d5246ac3.png">

**Comment by GrzegorzBednarski** [comment]
Even if we already have scroll, we can't scroll to very top items .

**Comment by GrzegorzBednarski** [comment]
Tested & accepted
