### ISSUE TITLE
Allow only integers in all numeric inputs

### ISSUE THREAD

**Issue by basia-wulnikowska** [wttech/cogboard#316]
### Description
In all inputs with numeric values allow only integers. Currently users are able to use symbols like "," which is not planned. Where to leave only integers:
- on board addition / edition - columns
- in widgets addition / edition - columns, rows (eg. Zabbix, Bamboo, Sonarqube, Jenkins)
- period time for widgets that need refreshes 

For QA: do full regression on all types of widgets - for numeric inputs check if only regexp for integers is allowed.

**Comment by GrzegorzBednarski** [comment]
Tested & accepted
