### ISSUE TITLE
Styling for disabled widgets

### ISSUE THREAD

**Issue by basia-wulnikowska** [wttech/cogboard#317]
### Description
Currently disabling widgets does not work as expected. We need to work on both backend and frontend side:
- backend: stop refreshing widget if it's set up as disabled. No new data should be taken for this widget in that case. During testing: QA to check dev tools if network does not show new requests for disabled widget
- frontend: make disabled widgets greyed out, with "Disabled" information and some new icon for that type of widget.

**Comment by GrzegorzBednarski** [comment]
Please align icon with other ones and add "Widget disabled" text. Check icon styling with and without "expandable" option.
Align disabled widget with missconfiguration error and other ones.

**Comment by GrzegorzBednarski** [comment]
Tested & accepted
