### ISSUE TITLE
Redundant .version file

### ISSUE THREAD

**Issue by apiotrowski312** [wttech/cogboard#328]
Hello! I found a bug (and I have a feature proposal).

**Bug**: There is no **.version** file on your 1.0.1 release. Project will not start because of that.

**Feature**: As a administrator, If I would see information, that there is new version available, I would prefer simply bump versions in my docker-compose.yml. And that should be all. Right now I have to bump version inside .version file also which is IMO redundant.

 I think you could inject .version file while building image (with --build-args flag) and echo it to file somewhere. This way you will be able to use simple docker-compose.yml without any additional files

**Comment by szymon-owczarzak** [comment]
I will have a look at how to fix this.
