### ISSUE TITLE
Guest login support

### ISSUE THREAD

**Issue by szymon-owczarzak** [wttech/cogboard#336]
### Short Description
Give users the option to login as a guest so upcoming features Planning Poker & Retro Board can identify users and use their name.

#### Solution (optional)
Extend Login dialog with a checkbox: `Login as Guest`. When the new option is selected password field is hidden and Login button changes its behavior. Instead of sending a login request it saves the given user name in session storege.
Username is shown in the app bar.

### Acceptance Criteria
 - [x] User can login as a guest without password
 - [x] Username is displayed in the app bar
 - [x] User name is cleared when window is closed or when user clicks logout.

![image](https://user-images.githubusercontent.com/25975896/109783055-dbda5180-7c09-11eb-9150-341c1cca3dc2.png)

**Comment by GrzegorzBednarski** [comment]
Username is displayed in notification bar after login. It's acceptable solution
