### ISSUE TITLE
Allow starting existing board

### ISSUE THREAD

**Issue by devzbysiu** [wttech/cogboard#340]
### Describe the bug
Currently, when starting a board, the script is checking if the board with inserted name already exists. If it exists, the job stops and asks for new name. It should start existing board instead of creating new one. This way re-started projects can get back to their boards quickly.

 ### To Reproduce
1. Go to jenkins
2. Click on starting board job
3. Insert name of existing board and start the job
4. See the error in the job logs

### Expected behavior
The job should restart existing board instead of failing.

### Desktop (please complete the following information):
N/A

**Comment by devzbysiu** [comment]
Done. The job now works like this:
- if the board doesn't exist, the job will create and start it
- if the board exists, but is disabled, the job will start the board
- if the board exists and is started, the job will fail

**Comment by GrzegorzBednarski** [comment]
Tested & accepted
