### ISSUE TITLE
Show inactive boards

### ISSUE THREAD

**Issue by devzbysiu** [wttech/cogboard#341]
### Short Description
When a new board is generated, the static website is updated to reflect this change. However, this website does not contain inactive boards and it makes things harder when the board should be re-started.

#### Solution (optional)
Add some kind of switch/filter to the static website to show inactive boards as well.

### Acceptance Criteria
 - [x] User can see inactive boards on the board listing page
 - [x] User can see active boards on the board listing page
 - [x] User can switch between those views

**Comment by devzbysiu** [comment]
Done. Ready for testing.

**Comment by GrzegorzBednarski** [comment]
Tested & accepted
