### ISSUE TITLE
LogsViewer - button in log record for filtering similar logs

### ISSUE THREAD

**Issue by TheTerabit** [wttech/cogboard#388]
### Short Description
After expanding a log, there is a button displayed on the right side which proposes creation of filter.

### Acceptance Criteria
 - [ ] Button in expanded log record in logs table
 - [ ] Clicking the button opens modal
 - [ ] Wildcard field is filled automaticly, proposing filtering for similar logs
 - [ ] [TBD] we need some examples of created wildcards as AC

**Comment by szymon-owczarzak** [comment]
This ticket requires further investigation about how to create a wildcard from a log entry.
